# user-specified paths
local_structures_dir: 'C:/Users/mikem/crystals/clusters/cluster_structures/'
local_crystals_dir: 'C:/Users/mikem/crystals/clusters/crystals_reference/'
local_ltemplify_path: 'C:/Users/mikem/miniconda3/envs/LAMMPS_runs/lib/site-packages/moltemplate/ltemplify.py'

cluster_structures_dir: '/vast/mk8347/molecule_clusters/'
cluster_crystals_dir: '/scratch/mk8347/lammps_prep/crystals_reference/'
cluster_ltemplify_path: '~/.local/bin/ltemplify.py'